### ISSUE TITLE
Request: Add info about Graylog 3.1 compatibility

### ISSUE THREAD

**Issue by biohazardxxx** [nitrotm/graylog-plugin-influxdb#1]
Hi, can you please add info about the Graylog 3.1 compatibility of this plugin?
Best regards
Bio

**Comment by biohazardxxx** [comment]
Also it would be good to know the supported influxDB version.

**Comment by nitrotm** [comment]
It's compatible with Graylog >= 2.x as stated in the readme.

I've added a note that this works with InfluxDB 1.x (for 2.x, it will require another client library but I am not interested to make the switch as long as 2.x is in beta).

**Comment by biohazardxxx** [comment]
Thanks a lot!
